### PR TITLE
Fix borken proj reference

### PR DESCRIPTION
**Pull request by pouladpld**
*nix file systems are case sensitive

### CODE REVIEW

**Comment by JuergenGutsch** [comment]
Hi @pouladpld 
Many thanks for the PR :-)
What is the reason to remove the global.json?

**Comment by pouladpld** [comment]
Hey. I removed it because it enforces a specific version that I don't have installed.

**Comment by JuergenGutsch** [comment]
Makes kinda sense :-)
I wanted to avoid that some folks use version smaller than 2.0.

**Comment by pouladpld** [comment]
It seems good now.

**Comment by JuergenGutsch** [comment]
Yes, Thanks a lot :-)

**Pull request merged**
