### PR TITLE
GraphQl.AspNetCore v2.1.0

### PR DESCRIPTION
**Pull request by poulad**

### CODE REVIEW

**Comment by JuergenGutsch** [comment]
Hi @poulad Many thanks for your PR :-)

**Comment by poulad** [comment]
Oh. Deployment went bad. It deployed the wrong package version.

**Comment by JuergenGutsch** [comment]
Oh, you are right. The merge was wrong, should be merged to develop instead AND the feature branches should be created based on develop instead of master.

**Comment by JuergenGutsch** [comment]
I just unlisted the packages on NuGet and will revert the merge

**Comment by poulad** [comment]
Tbh, I don't like controlling the version from app veyor file. It's already in the csproj file. 
I also publish from AppVeyor in my own projects as well but don't override the version on AppVeyor.

**Comment by JuergenGutsch** [comment]
It's only the last number here. but I completely agree with you. I also moved back from using the build number in the version numbers, except in pre-releases. I never changed it here in this project. Shame on me!

* 1.0.5 will be a release number
* 1.0.6-build66 will be a pre-release number
(This works pretty good in the current projects)

I'm going to fix this within the next two days. Thursday probably. Since I use GitFlow I'll set the version number in the release branch.

**Pull request merged**
