### PR TITLE
Re-work configuration

### PR DESCRIPTION
**Pull request by johnrutherford**
After learning more about GraphQL and graphql-dotnet, I did things a little differently than I had originally planned in #8.

I know this is a lot of changes. In retrospect, I should have split up these changes better. But I've tried to summarize all of the changes here:

## Re-work configuration

I added a way to easily configure GraphQL schemas in `ConfigureServices`. This follows the pattern of newer .NET Core components where you configure/register services with "AddXxx" in `ConfigureServices()` and then add them to the pipeline with "UseXxx" in `Configure()`. 

Users can now easily configure more than just the Query type of a schema. Also, configuring this separately means that this configuration can be re-used for exposing over another kind of endpoint (like a [socket endpoint](https://github.com/aspnet/SignalR/tree/dev/src/Microsoft.AspNetCore.Sockets)).

All graph types are resolved from the dependency injection container.

The `UseGraphQl()` extension method now requires the path to specified explicitly. 

## Parse request parameters per spec

I reviewed the[ specs for parsing GraphQL requests](http://graphql.org/learn/serving-over-http/#http-methods-headers-and-body) and made some changes to the middleware to follow the spec. Now "variables" and "operationName" are supported.

## Log errors rather than throw exception

According to the [spec](http://graphql.org/learn/serving-over-http/#response), all errors should be returned to the client. So I made changes to log these errors, but not create exceptions and throw which will result in a 500 error being returned to the client.

## Graphiql

I updated the configuration to require the path. 

I removed the commented out `JSON.stringify()` statements so it would work with the middleware now that it more closely follows the spec for request parsing.

### CODE REVIEW

**Comment by JuergenGutsch** [comment]
I like your changes a lot. Yes there are a lot of changes. This is why I checked out your work and tried it locally. Unfortunately there is a pretty small problem:
The "SchemaConfiguration" isn't created with a name, so the method "GetSchemaProvider" will fail, because there's no Schema with the name "Default"

What do you think about that?
```
services.AddGraphQl("Default", schema =>
{
    schema.SetQueryType<BooksQuery>();
});
```
(This method could be renamed to "AddGraphQlSchema")

The AddGraphQL than looks like this:
```
public static IGraphQlBuilder AddGraphQl(
    this IServiceCollection services, 
    string schemaName,
    Action<SchemaConfiguration> configure)
{
    if (services == null)
        throw new ArgumentNullException(nameof(services));

    if (configure == null)
        throw new ArgumentNullException(nameof(configure));

    if (String.IsNullOrWhiteSpace(schemaName))
        throw new ArgumentNullException(nameof(schemaName));

    var builder = new GraphQlBuilder(services);

    var schema = new SchemaConfiguration(schemaName);
    configure(schema);

    return builder.AddSchema(schema);
}
```
This will definetely work :-)

**Comment by JuergenGutsch** [comment]
BTW: don't worry about the failing build. I still need to fix the build #6

**Comment by johnrutherford** [comment]
I had forgotten to comment out the SchemaName line in the demo app. The idea is that you create a default schema will a `null` name. Most people will only ever need one, so I wanted to make that use case as simple as possible. Then if you need an additional one, they get named and you need to specify the name on the middleware options.

**Comment by JuergenGutsch** [comment]
But the "Name" property on the SchemaConfiguration is read-only and cannot be set

**Comment by johnrutherford** [comment]
Yes, but `ServiceCollectionExtensions.AddGraphQl()` creates the default `SchemaConfiguration` with a `null` name. Then you can add additional named schemas through `IGraphQlBuilder`. 

Like this:

```
services.AddGraphQl(schema =>
{
    schema.SetQueryType<BooksQuery>();
})
.AddSchema("Other", schema =>
{
    schema.SetQueryType<OtherQuery>();
});
```

So then when you add the middleware, you leave `SchemaName` on the options null if you're just using the default schema.

**Comment by JuergenGutsch** [comment]
ok. got it. 👍

**Pull request merged**
