### PR TITLE
Multipart file upload and JWT token support to graphiql

### PR DESCRIPTION
**Pull request by traqel**

### CODE REVIEW

**Review by JuergenGutsch — APPROVED** [review]

**Comment by JuergenGutsch** [comment]
Hi @traqel
Many Thanks for your PR. 
Would you please update your PR and solve the conflicts? I'd really like to merge it :-)

**Comment by traqel** [comment]
> Hi @traqel
> Many Thanks for your PR.
> Would you please update your PR and solve the conflicts? I'd really like to merge it :-)

Sure, will do ASAP -)

**Comment by JuergenGutsch** [comment]
Great. Thanks :-)

**Comment by JuergenGutsch** [comment]
Hi @traqel 
I just tried to merge it locally on my machine but I got some errors which make it hard to merge. 
Would you please merge the latest changes from develop and try to solve the merge errors? 
That would be super cool :-)

**Comment by tigranarakelyan** [comment]
> Hi @traqel
> I just tried to merge it locally on my machine but I got some errors which make it hard to merge.
> Would you please merge the latest changes from develop and try to solve the merge errors?
> That would be super cool :-)

Hi @JuergenGutsch 

I have realized that I can improve my solution. Currently, the mutation for file upload has a dependency from AspNetCore.App, which is not elegant. Also wants to add file upload usage example to demo project.

**Comment by JuergenGutsch** [comment]
Hey
Thank you very much for the PR and the improvements. I really appreciate that.
I just merged your PR in.

**Pull request merged**
